name: restlib_http_connector
description: library for binding restlib applications to dart's HTTP server
dependencies:
  logging: any
  restlib_common:
    git: https://code.google.com/p/dart-restlib.common/
  restlib_core:
    git: https://code.google.com/p/dart-restlib.core/
  restlib_server:
    git: https://code.google.com/p/dart-restlib.server/
dev_dependencies:
  restlib_testing:
    git: https://code.google.com/p/dart-restlib.testing/
